[package]
name = "download_ffi"
version = "0.1.0"
edition = "2024"
authors = ["Axel '0vercl0k' Souchet"]

[dependencies]
ureq = { version = "3.4", default-features = false, features = ["rustls"] }
serde_json = "1.0"
zip = { version = "8.6", default-features = false, features = ["deflate"] }

[lints.clippy]
pedantic = "warn"
