#!/bin/bash

function check_var
{
    if [[ ! -v $1 ]]; then echo "Specify $1 in vars"; exit; fi;
}

export WTF=`pwd`/../..
export PYTHONPATH=${PYTHONPATH}:${WTF}/linux_mode/scripts

KERNEL=vmlinux-5.13.12

# all vars must to be specified
# QEMU_SYSTEM_X86_64=/home/marat/null/qemu/build/qemu-system-x86_64
# VM_IP=192.168.122.15
# WTF_BUILD_PATH=/home/marat/Documents/work/wtf/wtf-test/src/build

VM_HOME=/home

WTF_BUILD_PATH=/home/marat/Documents/work/wtf/wtf-test/src/build
WTF=${WTF_BUILD_PATH}/wtf

check_var QEMU_SYSTEM_X86_64
check_var VM_IP
check_var VM_HOME
check_var WTF