
// Copyright (c) 2010-2019 niXman (i dot nixman dog gmail dot com). All
// rights reserved.
//
// This file is part of YAS(https://github.com/niXman/yas) project.
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//
//
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef __yas__std_types_hpp
#define __yas__std_types_hpp

#include <yas/detail/config/config.hpp>

#include <yas/types/std/pair.hpp>
#include <yas/types/std/bitset.hpp>
#include <yas/types/std/chrono.hpp>
#include <yas/types/std/optional.hpp>
#include <yas/types/std/complex.hpp>
#include <yas/types/std/string.hpp>
#include <yas/types/std/string_view.hpp>
#include <yas/types/std/wstring.hpp>
#include <yas/types/std/vector.hpp>
#include <yas/types/std/list.hpp>
#include <yas/types/std/forward_list.hpp>
#include <yas/types/std/map.hpp>
#include <yas/types/std/set.hpp>
#include <yas/types/std/deque.hpp>
#include <yas/types/std/multimap.hpp>
#include <yas/types/std/multiset.hpp>
#include <yas/types/std/array.hpp>
#include <yas/types/std/tuple.hpp>
#include <yas/types/std/variant.hpp>
#include <yas/types/std/unordered_set.hpp>
#include <yas/types/std/unordered_map.hpp>
#include <yas/types/std/unordered_multiset.hpp>
#include <yas/types/std/unordered_multimap.hpp>

#endif // __yas__std_types_hpp
